#!/usr/bin/env python3
"""
Train and evaluate a compact graph neural network for agglomerate morphology.

OVERVIEW
--------
This script trains a graph neural network (GNN) using the particle-contact
graphs stored in::

    DATASET/case_*/graph.npz

It supports two principal applications:

1. Training and evaluating the main model using all available agglomerates.
2. Performing additional analyses, such as:
   - training only on agglomerates with a fixed particle count;
   - comparing a minimal feature set with all stored graph features;
   - testing different latent-space dimensions;
   - comparing contact-only graphs with all reported adhesive interactions.

The model predicts one structural target:

    - mean_geometric_exposure

The predictions are made exclusively through a learned latent bottleneck.
No precomputed aggregate-level descriptors are supplied to the prediction
head.

The script evaluates candidate latent dimensions using grouped cross-validation
and automatically selects the smallest latent dimension whose mean out-of-fold
R² lies within ``--selection-tolerance`` of the best candidate.

REQUIREMENTS
------------
The required Python packages are:

    numpy
    matplotlib
    torch
    torch_geometric

For example, PyTorch Geometric can be installed after installing the
appropriate PyTorch version for the local system. See:

    https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html

EXPECTED DATASET STRUCTURE
--------------------------
The input directory must contain one subdirectory per agglomerate:

    gnn_dataset/
    ├── case_001_.../
    │   └── graph.npz
    ├── case_002_.../
    │   └── graph.npz
    └── ...

Each ``graph.npz`` file must contain:

    node_features
    edge_index
    edge_features
    positions
    targets

The following name arrays should also be included:

    node_feature_names
    edge_feature_names
    target_names

The graph files must already have been generated by the preprocessing
workflow. This script does not generate agglomerates, run DEM simulations,
or construct graph.npz files from VTK data.

BASIC USE: COMPLETE ANALYSIS
----------------------------
To train the main model using all available agglomerates and the default
minimal feature set, run:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset

By default, the script:

    - uses all valid graph.npz files;
    - uses the minimal graph feature set;
    - tests latent dimensions 1, 2, 3 and 4;
    - performs grouped five-fold cross-validation;
    - keeps all realizations of the same parameter combination in one fold;
    - trains for up to 300 epochs;
    - uses validation-based early stopping;
    - applies random rigid rotations during training;
    - selects the latent dimension automatically;
    - creates prediction tables, metrics, figures and trained models.

The default minimal feature set contains:

Node scalars:
    - radial_distance_over_rg
    - coordination

Edge scalars:
    - distance_over_dref

In addition, the model always uses:

    - normalized particle coordinates;
    - relative-position vectors along graph edges;
    - graph connectivity.

Consequently, stored force, torque, overlap, gap and contact-area quantities
are not used by the minimal model.

MAIN OUTPUT DIRECTORY
---------------------
The complete analysis with minimal features is written to:

    gnn_dataset/
    └── additional_analyses/
        └── all_particle_counts/
            └── minimal/

Important output files include:

    latent_dimension_comparison.csv
        Performance of every tested latent dimension.

    latent_dimension_comparison.png
        Graphical comparison of the candidate latent dimensions.

    predictions.csv
        Combined out-of-fold predictions and fold-specific latent values.

    training_metrics.json
        Model settings, selected latent dimension and evaluation metrics.

    gnn_oof_performance.png
        Out-of-fold parity plot for mean geometric exposure.

    gnn_fold_rmse.png
        Variation of the prediction error among the test folds.

    model_fold_0.pt, ..., model_fold_4.pt
        Selected trained model from every cross-validation fold.

    latent_dimension_sweep/
        Detailed outputs and models for every tested latent dimension.

FIXED-PARTICLE-COUNT ANALYSIS
-----------------------------
To repeat the complete latent-dimension study using only agglomerates with
200 particles, run:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --particle-count 200

The particle count is determined from the actual number of graph nodes and
not from the case filename.

If the complete dataset contains 45 agglomerates with N = 200, only those
45 graphs will be used. The remaining graphs are left unchanged.

The results are written separately to:

    gnn_dataset/
    └── additional_analyses/
        └── fixed_N_200/
            └── minimal/

This analysis does not overwrite the results obtained from all agglomerates.

The fixed-N analysis should be treated as an additional investigation of
whether the GNN distinguishes morphology after the dominant variation in
particle count has been removed. The latent dimension is selected again for
this subset; it is not automatically fixed to the value selected from the
complete dataset.

FEATURE-SET COMPARISON
----------------------
The default setting is:

    --feature-set minimal

To repeat the analysis using every node and edge feature stored in graph.npz,
run:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --feature-set stored

For the fixed-N = 200 subset, use:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --particle-count 200 \
        --feature-set stored

These results are written to:

    additional_analyses/all_particle_counts/stored/

or:

    additional_analyses/fixed_N_200/stored/

The minimal and stored models should be compared using the same architecture,
folds, random seed and latent-dimension candidates. If both models perform
similarly, the additional stored contact quantities do not provide useful
information for the present geometric targets.

Note that ``--feature-set stored`` can only use features that are actually
contained in graph.npz. If preprocessing stored only the three node features
and two edge features used in the original workflow, DEM forces and torques
are already absent from the training data.

LATENT-DIMENSION SELECTION
--------------------------
The default candidates are:

    --latent-candidates 1 2 3 4

For each candidate, the complete grouped cross-validation procedure is
performed. The script then selects the smallest latent dimension whose mean
out-of-fold R² is within 0.02 of the best result.

A different candidate range can be supplied, for example:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --latent-candidates 1 2 3 4 5 6

The selection tolerance can also be changed:

    --selection-tolerance 0.01

The ``--latent`` option bypasses the latent-dimension sweep and trains only
one prescribed dimension:

    --latent 1

This option is useful for reproducing an already selected configuration, but
it should not be used when the latent dimension still needs to be determined.

RECOMMENDED PUBLICATION RUNS
----------------------------
The following four runs provide the main model and the most relevant
additional comparisons.

1. All agglomerates with minimal features:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --feature-set minimal \
        --latent-candidates 1 2 3 4

2. All agglomerates with every stored feature:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --feature-set stored \
        --latent-candidates 1 2 3 4

3. Fixed N = 200 with minimal features:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --particle-count 200 \
        --feature-set minimal \
        --latent-candidates 1 2 3 4

4. Fixed N = 200 with every stored feature:

    python3 train_gnn_pure_graph_latent_v9.py /path/to/gnn_dataset \
        --particle-count 200 \
        --feature-set stored \
        --latent-candidates 1 2 3 4

Do not change the architecture between the minimal and stored-feature runs.
Otherwise, the influence of the feature set cannot be separated from the
influence of the network architecture.

GROUPED CROSS-VALIDATION
------------------------
By default, graph realizations belonging to the same physical parameter
combination are placed in the same test fold. This prevents closely related
realizations from appearing simultaneously in the training and test data.

The option:

    --random-folds

disables this grouping. Random folds should be used only as a diagnostic
comparison and not as the main publication result.

MODEL ARCHITECTURE
------------------
The default architecture can be changed using:

    --hidden 64
    --layers 6
    --dropout 0.1
    --batch-size 16

For a clean comparison between two feature sets, use identical values for
these options.

A smaller model may be explored for the fixed-N subset, for example:

    --hidden 32 --layers 3

However, this constitutes a separate architecture study. It should not be
combined with a feature-ablation comparison unless the same reduced
architecture is used for all compared feature sets.

CONTACT DEFINITION
------------------
By default, message passing is restricted to geometrically touching or
numerically near-touching particle pairs. A pair is retained when:

    delta / d_ref >= -contact_overlap_tolerance

The default tolerance is:

    --contact-overlap-tolerance 1e-6

To include every reported adhesive interaction, including separated
near-neighbour pairs, use:

    --include-non-touching

This is intended as an additional sensitivity analysis. The contact-only graph
should normally remain the primary representation when the targets are defined
using the geometrical contact network.

OTHER USEFUL OPTIONS
--------------------
Use a different number of folds:

    --folds 3

Increase the maximum number of epochs:

    --epochs 500

Change the random seed:

    --seed 17

Change the early-stopping patience:

    --patience 75

Disable random rotation augmentation:

    --no-rotation-augmentation

Skip figure generation:

    --no-plots

Write results to a user-defined location:

    --output-directory /path/to/output_directory

EXAMPLE: FIXED N = 200 WITH CUSTOM OUTPUT
-----------------------------------------
A complete example is:

    python3 train_gnn_pure_graph_latent_v9.py \
        /path/to/gnn_dataset \
        --particle-count 200 \
        --feature-set minimal \
        --latent-candidates 1 2 3 4 \
        --folds 5 \
        --hidden 64 \
        --layers 6 \
        --seed 7 \
        --output-directory /path/to/results/fixed_N_200_minimal

INTERPRETING THE RESULTS
------------------------
The principal quantity for selecting the latent dimension is the out-of-fold
R² for mean geometric exposure. RMSE and MAE should also be
reported, particularly for the fixed-N analysis, because the target variation
within one particle-count class can be substantially smaller than in the
complete dataset.

The fixed-N analysis should answer:

    Can the graph model predict differences between agglomerates when particle
    count is identical?

The feature-set comparison should answer:

    Do the additional stored particle and contact variables improve prediction
    beyond a minimal geometry-and-connectivity representation?

The fixed-N analysis is supplementary to the complete 135-agglomerate study.
It should not replace the main analysis.

REPRODUCIBILITY NOTE
--------------------
The script seeds Python, NumPy and PyTorch. However, GPU operations and some
PyTorch Geometric routines may still show small numerical differences between
systems. The complete command, software versions and generated
training_metrics.json file should therefore be retained for every reported
run.
"""

import argparse
import csv
import json
import random
import re
import shutil
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, ListedColormap
import torch
from torch import nn
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import (
    GINEConv,
    global_add_pool,
    global_max_pool,
    global_mean_pool,
)


GRAPH_TARGET_FALLBACK = [
    "mean_graph_depth",
    "shielded_fraction_h_ge_2",
    "accessibility_score",
    "mean_geometric_exposure",
]
EXPOSURE_TARGET = "mean_geometric_exposure"

TARGET_LABELS = {
    EXPOSURE_TARGET: r"Mean geometric exposure $\overline{a}_{\mathrm{geo}}$",
}


def string_list(array, fallback):
    if array is None:
        return list(fallback)
    return [str(value) for value in np.asarray(array).tolist()]


def normalized_feature_name(name):
    """Normalize feature labels so harmless naming differences still match."""
    return re.sub(r"[^a-z0-9]+", "", str(name).lower())


def select_named_features(values, names, requested, kind):
    """Return selected columns and their original labels."""
    lookup = {normalized_feature_name(name): index for index, name in enumerate(names)}
    indices = []
    selected_names = []
    missing = []
    for requested_name in requested:
        key = normalized_feature_name(requested_name)
        if key not in lookup:
            missing.append(requested_name)
        else:
            index = lookup[key]
            indices.append(index)
            selected_names.append(names[index])
    if missing:
        raise ValueError(
            f"Requested {kind} feature(s) not found: {missing}. "
            f"Available {kind} features: {names}"
        )
    return values[:, indices], selected_names


def minimal_feature_selection(node, node_names, edge, edge_names):
    """Keep only nonconstant structural scalars; coordinates are added later."""
    node, node_names = select_named_features(
        node,
        node_names,
        ["radial_distance_over_rg", "coordination"],
        "node",
    )
    edge, edge_names = select_named_features(
        edge,
        edge_names,
        ["distance_over_dref"],
        "edge",
    )
    return node, node_names, edge, edge_names


class Model(nn.Module):
    """Pure graph GNN whose targets are predicted only from the latent vector."""

    def __init__(self, nin, ein, nout, global_dim=0, hidden=64, latent=4,
                 layers=6, dropout=0.1):
        super().__init__()
        # Three normalized coordinates and three relative-vector components
        # are added dynamically to the stored node and edge features.
        self.node = nn.Linear(nin + 3, hidden)
        self.edge = nn.Linear(ein + 3, hidden)
        self.layers = nn.ModuleList([
            GINEConv(nn.Sequential(
                nn.Linear(hidden, hidden), nn.ReLU(), nn.Linear(hidden, hidden)
            ))
            for _ in range(layers)
        ])
        self.norms = nn.ModuleList([nn.LayerNorm(hidden) for _ in range(layers)])
        self.dropout = nn.Dropout(dropout)
        # The graph-derived representation is the model's only information
        # path. No precomputed aggregate descriptors are supplied to either
        # the latent bottleneck or the prediction head.
        self.to_latent = nn.Linear(3 * hidden, latent)
        self.head = nn.Sequential(
            nn.Linear(latent, 16), nn.ReLU(), nn.Linear(16, nout)
        )

    def forward(self, data):
        source, target = data.edge_index
        relative_vector = data.pos[target] - data.pos[source]
        x = self.node(torch.cat((data.x, data.pos), dim=1))
        edge = self.edge(torch.cat((data.edge_attr, relative_vector), dim=1))
        for layer, norm in zip(self.layers, self.norms):
            update = self.dropout(torch.relu(layer(x, data.edge_index, edge)))
            x = norm(x + update)
        count = global_add_pool(torch.ones_like(x[:, :1]), data.batch)
        graph_pooled = torch.cat((
            global_mean_pool(x, data.batch),
            global_max_pool(x, data.batch),
            global_add_pool(x, data.batch) / torch.sqrt(count.clamp_min(1.0)),
        ), dim=1)
        latent = self.to_latent(graph_pooled)
        return self.head(latent), latent


def graph_paths(root):
    # Current preprocessing layout: gnn_dataset/case_.../graph.npz
    paths = sorted(root.glob("case_*/graph.npz"))
    if not paths:
        # Useful fallback if graphs were placed one level deeper.
        paths = sorted(root.rglob("graph.npz"))
    return paths


def realization_group(case_name):
    """Remove the realization suffix while retaining the physical parameters."""
    match = re.search(
        r"(?:^|_)dp([^_]+)_N([^_]+)_Df([^_]+)", case_name, flags=re.IGNORECASE
    )
    if match:
        return "dp{}_N{}_Df{}".format(*match.groups()).lower()
    name = re.sub(r"_rep(?:licate)?_?\d+$", "", case_name, flags=re.IGNORECASE)
    return re.sub(r"^case_\d+_", "", name, flags=re.IGNORECASE)


def make_grouped_folds(data, number_of_folds, seed):
    groups = {}
    for index, graph in enumerate(data):
        groups.setdefault(realization_group(graph.case), []).append(index)
    if len(groups) < number_of_folds:
        raise ValueError(
            f"Only {len(groups)} independent parameter groups are available for "
            f"{number_of_folds} grouped folds"
        )
    rng = np.random.default_rng(seed)
    group_items = list(groups.values())
    rng.shuffle(group_items)
    group_items.sort(key=len, reverse=True)
    folds = [[] for _ in range(number_of_folds)]
    for indices in group_items:
        smallest = min(range(number_of_folds), key=lambda i: len(folds[i]))
        folds[smallest].extend(indices)
    return [np.asarray(fold, dtype=int) for fold in folds]


def load_dataset(root, contact_overlap_tolerance=1.0e-6,
                 include_non_touching=False, feature_set="minimal"):
    data = []
    reference = None
    skipped = []

    for path in graph_paths(root):
        try:
            with np.load(path, allow_pickle=False) as arrays:
                node = np.asarray(arrays["node_features"], dtype=np.float32)
                edge_index = np.asarray(arrays["edge_index"], dtype=np.int64)
                edge = np.asarray(arrays["edge_features"], dtype=np.float32)
                targets = np.asarray(arrays["targets"], dtype=np.float32).reshape(-1)
                if "positions" not in arrays:
                    raise ValueError(
                        "graph.npz has no 'positions' array; rerun preprocessing "
                        "with particle positions enabled"
                    )
                position = np.asarray(arrays["positions"], dtype=np.float32)
                node_names = string_list(
                    arrays["node_feature_names"] if "node_feature_names" in arrays else None,
                    [f"node_{i}" for i in range(node.shape[1])],
                )
                edge_names = string_list(
                    arrays["edge_feature_names"] if "edge_feature_names" in arrays else None,
                    [f"edge_{i}" for i in range(edge.shape[1])],
                )
                target_names = string_list(
                    arrays["target_names"] if "target_names" in arrays else None,
                    GRAPH_TARGET_FALLBACK,
                )

            if node.ndim != 2 or edge.ndim != 2 or edge_index.shape[0] != 2:
                raise ValueError(
                    f"invalid shapes: node={node.shape}, edge={edge.shape}, "
                    f"edge_index={edge_index.shape}"
                )
            if edge.shape[0] != edge_index.shape[1]:
                raise ValueError("edge_features rows do not match edge_index columns")
            if position.shape != (node.shape[0], 3):
                raise ValueError(f"invalid particle-position shape: {position.shape}")
            if len(target_names) != len(targets):
                raise ValueError("target_names and targets have different lengths")
            if EXPOSURE_TARGET not in target_names:
                raise ValueError(
                    f"required target {EXPOSURE_TARGET!r} is absent; "
                    f"available targets: {target_names}"
                )
            exposure_index = target_names.index(EXPOSURE_TARGET)
            targets = targets[[exposure_index]]
            target_names = [EXPOSURE_TARGET]
            if not all(np.isfinite(a).all() for a in (node, edge, position, targets)):
                raise ValueError("graph contains NaN or infinite values")

            # Centre positions and normalize them by the reference diameter.
            # If the first edge feature is distance/d_ref, d_ref follows from
            # the ratio of physical and normalized contact distances.
            centered = position - position.mean(axis=0, keepdims=True)
            if edge_index.shape[1] and edge.shape[1]:
                raw_distance = np.linalg.norm(
                    position[edge_index[1]] - position[edge_index[0]], axis=1
                )
                valid_scale = (edge[:, 0] > 1e-12) & (raw_distance > 1e-12)
                d_ref = float(np.median(raw_distance[valid_scale] / edge[valid_scale, 0])) \
                    if np.any(valid_scale) else 1.0
            else:
                d_ref = 1.0
            normalized_position = centered / max(d_ref, 1e-12)

            # Restrict message passing to geometrically touching (or
            # numerically near-touching) particle pairs.  The first stored node
            # feature is r_i/d_ref in the present graph format, so the
            # dimensionless geometrical overlap is obtained independently of
            # the adhesive interaction cut-off used by the DEM solver.
            if not include_non_touching and edge_index.shape[1]:
                normalized_radius = node[:, 0]
                normalized_distance = np.linalg.norm(
                    normalized_position[edge_index[1]]
                    - normalized_position[edge_index[0]], axis=1
                )
                normalized_overlap = (
                    normalized_radius[edge_index[0]]
                    + normalized_radius[edge_index[1]]
                    - normalized_distance
                )
                touching = normalized_overlap >= -contact_overlap_tolerance
                edge_index = edge_index[:, touching]
                edge = edge[touching]
                if edge_index.shape[1] == 0:
                    raise ValueError(
                        "contact-only filtering removed every graph edge"
                    )

            # Feature selection is intentionally performed after contact
            # filtering, because the stored radius is needed to decide which
            # reported adhesive pairs are geometrically touching.  Particle
            # coordinates and relative edge vectors are supplied separately
            # by the model and are retained for every feature set.
            stored_node_names = list(node_names)
            stored_edge_names = list(edge_names)
            if feature_set == "minimal":
                node, node_names, edge, edge_names = minimal_feature_selection(
                    node, node_names, edge, edge_names
                )

            signature = (node.shape[1], edge.shape[1], len(targets),
                         tuple(node_names), tuple(edge_names), tuple(target_names))
            if reference is None:
                reference = signature
            elif signature != reference:
                raise ValueError(
                    "feature layout differs from the first graph; rerun preprocessing "
                    "with consistent VTK fields"
                )

            graph = Data(
                x=torch.from_numpy(node),
                edge_index=torch.from_numpy(edge_index),
                edge_attr=torch.from_numpy(edge),
                pos=torch.from_numpy(normalized_position.astype(np.float32)),
                y=torch.from_numpy(targets).view(1, -1),
            )
            graph.case = path.parent.name
            data.append(graph)
        except Exception as exc:
            skipped.append({"path": str(path), "error": str(exc)})

    if reference is None:
        return data, None, skipped
    metadata = {
        "node_feature_count": reference[0],
        "edge_feature_count": reference[1],
        "target_count": reference[2],
        "node_feature_names": list(reference[3]),
        "edge_feature_names": list(reference[4]),
        "stored_node_feature_names": stored_node_names,
        "stored_edge_feature_names": stored_edge_names,
        "feature_set": feature_set,
        "target_names": list(reference[5]),
        "global_feature_names": [],
        "diagnostic_descriptor_names": [
            "log_particle_count",
            "log_radius_of_gyration_over_d_ref",
            "mean_coordination",
            "maximum_coordination",
        ],
        "latent_input": "graph_pooling_only",
        "global_feature_path": "not_used_by_model",
        "prediction_head_input": "latent_vector_only",
        "graph_pooling": "mean_max_and_size_normalized_add",
        "edge_selection": (
            "all_reported_pairs" if include_non_touching
            else "geometrically_touching_pairs"
        ),
        "contact_overlap_tolerance_over_d_ref": (
            None if include_non_touching else contact_overlap_tolerance
        ),
    }
    return data, metadata, skipped


def out_of_fold_metrics(predictions, target_names):
    """Calculate metrics from the combined test predictions of all folds."""
    truth = np.asarray([
        [row[f"true_{target}"] for target in target_names]
        for row in predictions
    ], dtype=float)
    predicted = np.asarray([
        [row[f"pred_{target}"] for target in target_names]
        for row in predictions
    ], dtype=float)

    residual = predicted - truth
    rmse = np.sqrt(np.mean(residual ** 2, axis=0))
    mae = np.mean(np.abs(residual), axis=0)
    ss_res = np.sum(residual ** 2, axis=0)
    ss_tot = np.sum((truth - np.mean(truth, axis=0)) ** 2, axis=0)
    r_squared = np.full_like(ss_tot, np.nan)
    valid = ss_tot > 0.0
    r_squared[valid] = 1.0 - ss_res[valid] / ss_tot[valid]

    return {
        target: {
            "rmse": float(rmse[index]),
            "mae": float(mae[index]),
            "r_squared": (
                float(r_squared[index]) if np.isfinite(r_squared[index]) else None
            ),
        }
        for index, target in enumerate(target_names)
    }


def plot_out_of_fold_predictions(predictions, target_names, metrics, output):
    """Create parity plots from the combined held-out predictions."""
    number = len(target_names)
    figure, axes = plt.subplots(1, number, figsize=(4.75 * number, 4.5))
    figure.subplots_adjust(
        left=0.065, right=0.925, bottom=0.15, top=0.94, wspace=0.16
    )
    axes = np.atleast_1d(axes)
    folds = np.asarray([row["fold"] for row in predictions], dtype=int)
    fold_ids = np.unique(folds)

    # The fold index is categorical.  Use exactly one colour bin per fold
    # instead of allowing Matplotlib to interpolate through all ten colours
    # of ``tab10`` between the minimum and maximum fold indices.
    base_colours = plt.get_cmap("tab10").colors
    fold_cmap = ListedColormap(
        [base_colours[index % len(base_colours)] for index in range(len(fold_ids))]
    )
    fold_boundaries = np.arange(len(fold_ids) + 1) - 0.5
    fold_norm = BoundaryNorm(fold_boundaries, fold_cmap.N)
    fold_to_colour_index = {
        fold_id: index for index, fold_id in enumerate(fold_ids)
    }
    fold_colours = np.asarray([fold_to_colour_index[value] for value in folds])

    for axis, target in zip(axes, target_names):
        truth = np.asarray([row[f"true_{target}"] for row in predictions])
        predicted = np.asarray([row[f"pred_{target}"] for row in predictions])
        lower = float(min(truth.min(), predicted.min()))
        upper = float(max(truth.max(), predicted.max()))
        margin = 0.05 * max(upper - lower, 1e-8)

        scatter = axis.scatter(
            truth, predicted, c=fold_colours, cmap=fold_cmap, norm=fold_norm, s=34,
            alpha=0.82, edgecolors="black", linewidths=0.3
        )
        axis.plot(
            [lower - margin, upper + margin],
            [lower - margin, upper + margin],
            color="black", linestyle="--", linewidth=1.1,
            label="Ideal prediction",
        )
        axis.set_xlim(lower - margin, upper + margin)
        axis.set_ylim(lower - margin, upper + margin)
        axis.set_aspect("equal", adjustable="box")
        axis.set_xlabel("Reference", fontsize=12)
        axis.set_ylabel("Out-of-fold prediction", fontsize=12)
        axis.set_title(
            TARGET_LABELS.get(target, target.replace("_", " ")), fontsize=13
        )
        axis.tick_params(labelsize=11)
        values = metrics[target]
        axis.text(
            0.04, 0.96,
            rf"$R^2={values['r_squared']:.3f}$" + "\n"
            + rf"$\mathrm{{RMSE}}={values['rmse']:.3f}$" + "\n"
            + rf"$\mathrm{{MAE}}={values['mae']:.3f}$",
            transform=axis.transAxes, va="top", ha="left", fontsize=10.5,
            bbox={"boxstyle": "round", "facecolor": "white", "alpha": 0.88},
        )
        axis.grid(alpha=0.2)

    colourbar = figure.colorbar(
        scatter, ax=axes.tolist(), ticks=np.arange(len(fold_ids)),
        boundaries=fold_boundaries, spacing="uniform", shrink=0.84, pad=0.02
    )
    colourbar.set_ticklabels([str(value + 1) for value in fold_ids])
    colourbar.ax.tick_params(labelsize=11)
    colourbar.set_label("Held-out test fold", fontsize=12)
    figure.savefig(output, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_fold_rmse(fold_scores, target_names, output):
    """Show fold-to-fold RMSE variation using one scale per target."""
    scores = np.asarray(fold_scores, dtype=float)
    number = len(target_names)
    figure, axes = plt.subplots(
        1, number, figsize=(4.7 * number, 3.9), constrained_layout=True
    )
    axes = np.atleast_1d(axes)
    folds = np.arange(1, scores.shape[0] + 1)

    for index, (axis, target) in enumerate(zip(axes, target_names)):
        axis.bar(folds, scores[:, index], color="#3070B3", edgecolor="black")
        axis.axhline(
            scores[:, index].mean(), color="#D1495B", linestyle="--",
            linewidth=1.4, label="Fold mean",
        )
        axis.set_xticks(folds)
        axis.set_xlabel("Test fold")
        axis.set_ylabel("RMSE")
        axis.set_title(TARGET_LABELS.get(target, target.replace("_", " ")))
        axis.grid(axis="y", alpha=0.2)
        axis.legend(frameon=False)

    figure.suptitle("Variation of prediction error between test folds", fontsize=13)
    figure.savefig(output, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_latent_dimension_comparison(rows, target_names, output):
    """Plot out-of-fold R-squared against the latent dimension."""
    dimensions = [row["latent_dimension"] for row in rows]
    figure, axis = plt.subplots(figsize=(7.2, 4.8), constrained_layout=True)
    for target in target_names:
        values = [row[f"r_squared_{target}"] for row in rows]
        axis.plot(
            dimensions, values, marker="o", linewidth=1.8,
            label=TARGET_LABELS.get(target, target.replace("_", " ")),
        )
    axis.set_xticks(dimensions)
    axis.set_xlabel(r"Latent dimension $n_\lambda$")
    axis.set_ylabel(r"Combined out-of-fold $R^2$")
    axis.set_title("Selection of the latent morphology dimension")
    axis.grid(alpha=0.25)
    axis.legend(frameon=False)
    figure.savefig(output, dpi=300, bbox_inches="tight")
    plt.close(figure)


def rotate_positions(data):
    """Apply a random rigid rotation without changing distances or contacts."""
    matrix = torch.randn(3, 3, device=data.pos.device)
    q, _ = torch.linalg.qr(matrix)
    if torch.det(q) < 0:
        q[:, 0] *= -1
    data.pos = data.pos @ q.T
    return data


def write_prediction_csv(path, predictions):
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=predictions[0].keys())
        writer.writeheader()
        writer.writerows(predictions)


def run_cross_validation(data, metadata, skipped, folds, latent_dimension,
                         output_directory, args):
    """Train and evaluate one latent dimension using fixed outer folds."""
    output_directory.mkdir(parents=True, exist_ok=True)
    n_graphs = len(data)
    order = np.arange(n_graphs)
    predictions = []
    fold_scores = []
    best_epochs = []
    target_names = metadata["target_names"]

    for fold_index, test_indices in enumerate(folds):
        # Make the comparison reproducible while allowing each latent dimension
        # and fold to receive an independent initialization.
        run_seed = args.seed + 1000 * latent_dimension + fold_index
        random.seed(run_seed)
        np.random.seed(run_seed)
        torch.manual_seed(run_seed)

        train_indices = np.setdiff1d(order, test_indices)
        fold_rng = np.random.default_rng(args.seed + fold_index)
        shuffled_train = fold_rng.permutation(train_indices)
        n_validation = max(1, int(round(args.validation_fraction * len(shuffled_train))))
        validation_indices = shuffled_train[:n_validation]
        fit_indices = shuffled_train[n_validation:]
        train = [data[i] for i in fit_indices]
        validation = [data[i] for i in validation_indices]
        test = [data[i] for i in test_indices]

        y_train = torch.cat([graph.y for graph in train])
        mean = y_train.mean(dim=0)
        std = y_train.std(dim=0).clamp_min(1e-8)
        model = Model(
            nin=metadata["node_feature_count"],
            ein=metadata["edge_feature_count"],
            nout=metadata["target_count"],
            global_dim=len(metadata["global_feature_names"]),
            hidden=args.hidden,
            latent=latent_dimension,
            layers=args.layers,
            dropout=args.dropout,
        )
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)

        best_validation_loss = float("inf")
        best_state = None
        best_epoch = 0
        epochs_without_improvement = 0
        for epoch in range(args.epochs):
            model.train()
            loader = DataLoader(train, batch_size=min(args.batch_size, len(train)), shuffle=True)
            for batch in loader:
                if not args.no_rotation_augmentation:
                    batch = rotate_positions(batch)
                normalized_prediction, _ = model(batch)
                normalized_truth = (batch.y - mean) / std
                loss = ((normalized_prediction - normalized_truth) ** 2).mean()
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

            model.eval()
            validation_losses = []
            with torch.no_grad():
                for batch in DataLoader(validation, batch_size=len(validation), shuffle=False):
                    normalized_prediction, _ = model(batch)
                    normalized_truth = (batch.y - mean) / std
                    validation_losses.append(
                        float(((normalized_prediction - normalized_truth) ** 2).mean())
                    )
            validation_loss = float(np.mean(validation_losses))
            if validation_loss < best_validation_loss - 1e-6:
                best_validation_loss = validation_loss
                best_epoch = epoch + 1
                best_state = {
                    key: value.detach().cpu().clone()
                    for key, value in model.state_dict().items()
                }
                epochs_without_improvement = 0
            else:
                epochs_without_improvement += 1
                if epochs_without_improvement >= args.patience:
                    break

        if best_state is None:
            raise RuntimeError("Training ended without a valid validation state")
        model.load_state_dict(best_state)
        best_epochs.append(best_epoch)

        model.eval()
        squared_errors = []
        with torch.no_grad():
            for graph in test:
                # Never add fold-specific state to the graph stored in `data`.
                # A test graph in one fold becomes a training graph in another.
                evaluation_graph = graph.clone()
                evaluation_graph.batch = torch.zeros(
                    evaluation_graph.num_nodes, dtype=torch.long
                )
                normalized_prediction, latent = model(evaluation_graph)
                prediction = (
                    normalized_prediction[0] * std + mean
                ).cpu().numpy()
                truth = graph.y[0].cpu().numpy()
                squared_errors.append((prediction - truth) ** 2)
                row = {"case": graph.case, "fold": fold_index}
                for index, target in enumerate(target_names):
                    row[f"true_{target}"] = float(truth[index])
                    row[f"pred_{target}"] = float(prediction[index])
                for index, value in enumerate(latent[0].cpu().numpy()):
                    row[f"lambda_{index + 1}"] = float(value)
                predictions.append(row)

        fold_rmse = np.sqrt(np.mean(squared_errors, axis=0)).tolist()
        fold_scores.append(fold_rmse)
        torch.save({
            "state_dict": model.state_dict(),
            "metadata": metadata,
            "latent_dimension": latent_dimension,
            "hidden_dimension": args.hidden,
            "message_passing_layers": args.layers,
            "dropout": args.dropout,
            "best_epoch": best_epoch,
            "target_mean": mean,
            "target_std": std,
        }, output_directory / f"model_fold_{fold_index}.pt")
        print(
            f"  latent={latent_dimension}, fold={fold_index + 1}/{args.folds}: "
            f"best_epoch={best_epoch}, RMSE={fold_rmse}"
        )

    write_prediction_csv(output_directory / "predictions.csv", predictions)
    combined_metrics = out_of_fold_metrics(predictions, target_names)
    report = {
        **metadata,
        "n_graphs": n_graphs,
        "n_skipped": len(skipped),
        "skipped": skipped,
        "fold_rmse": fold_scores,
        "best_epoch_per_fold": best_epochs,
        "cross_validation": (
            "random" if args.random_folds else "grouped_by_parameter_case"
        ),
        "latent_dimension": latent_dimension,
        "mean_rmse": np.mean(fold_scores, axis=0).tolist(),
        "out_of_fold_metrics": combined_metrics,
        "warning": (
            "Grouped cross-validation is the reviewer-facing result. Random folds "
            "may be used only as a diagnostic comparison."
        ),
    }
    (output_directory / "training_metrics.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    return {
        "latent_dimension": latent_dimension,
        "predictions": predictions,
        "fold_scores": fold_scores,
        "report": report,
        "directory": output_directory,
    }


def comparison_row(result, target_names):
    row = {"latent_dimension": result["latent_dimension"]}
    r_squared_values = []
    for target in target_names:
        values = result["report"]["out_of_fold_metrics"][target]
        row[f"r_squared_{target}"] = values["r_squared"]
        row[f"rmse_{target}"] = values["rmse"]
        row[f"mae_{target}"] = values["mae"]
        if values["r_squared"] is not None:
            r_squared_values.append(values["r_squared"])
    row["mean_r_squared"] = (
        float(np.mean(r_squared_values)) if r_squared_values else None
    )
    return row


def print_latent_comparison(rows, target_names):
    print("\nLatent-dimension comparison (combined out-of-fold R-squared)")
    headings = ["latent"] + target_names + ["mean"]
    print(" | ".join(f"{heading:>25}" for heading in headings))
    print("-" * (29 * len(headings)))
    for row in rows:
        values = [row["latent_dimension"]]
        values.extend(row[f"r_squared_{target}"] for target in target_names)
        values.append(row["mean_r_squared"])
        formatted = [f"{int(values[0]):>25d}"]
        formatted.extend(
            f"{value:>25.4f}" if value is not None else f"{'undefined':>25}"
            for value in values[1:]
        )
        print(" | ".join(formatted))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("dataset", type=Path)
    parser.add_argument("--epochs", type=int, default=300)
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument(
        "--latent-candidates", type=int, nargs="+", default=[1, 2, 3, 4],
        help="Latent dimensions to compare; default: 1 2 3 4.",
    )
    parser.add_argument(
        "--latent", type=int, default=None,
        help="Run only one latent dimension (backward-compatible shortcut).",
    )
    parser.add_argument(
        "--selection-tolerance", type=float, default=0.02,
        help="Choose the smallest latent dimension within this mean-R2 distance "
             "of the best candidate.",
    )
    parser.add_argument("--hidden", type=int, default=64)
    parser.add_argument("--layers", type=int, default=6)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--validation-fraction", type=float, default=0.15)
    parser.add_argument("--patience", type=int, default=50)
    parser.add_argument("--no-rotation-augmentation", action="store_true")
    parser.add_argument(
        "--contact-overlap-tolerance", type=float, default=1.0e-6,
        help="Retain a pair when delta/d_ref >= -tolerance; default: 1e-6.",
    )
    parser.add_argument(
        "--include-non-touching", action="store_true",
        help="Use every reported adhesive interaction instead of a contact-only graph.",
    )
    parser.add_argument(
        "--feature-set", choices=("minimal", "stored"), default="minimal",
        help=(
            "Input scalars used by the GNN. 'minimal' keeps radial distance, "
            "coordination and edge distance; 'stored' keeps every feature in "
            "graph.npz. Normalized coordinates and relative vectors are used "
            "in both cases. Default: minimal."
        ),
    )
    parser.add_argument(
        "--particle-count", type=int, default=None,
        help=(
            "Retain only graphs with this number of particles, for example "
            "--particle-count 200. This is an additional fixed-N analysis."
        ),
    )
    parser.add_argument(
        "--output-directory", type=Path, default=None,
        help=(
            "Directory for results. By default, full/stored runs retain the "
            "legacy dataset-root output; other configurations use a separate "
            "analysis subdirectory."
        ),
    )
    parser.add_argument(
        "--no-plots", action="store_true",
        help="Train and write CSV/JSON results without generating figures.",
    )
    parser.add_argument(
        "--random-folds", action="store_true",
        help="Disable grouping of random realizations from the same parameter case.",
    )
    args = parser.parse_args()

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    root = args.dataset.resolve()
    if args.contact_overlap_tolerance < 0:
        raise SystemExit("--contact-overlap-tolerance must be non-negative")
    if args.particle_count is not None and args.particle_count < 1:
        raise SystemExit("--particle-count must be a positive integer")
    data, metadata, skipped = load_dataset(
        root,
        contact_overlap_tolerance=args.contact_overlap_tolerance,
        include_non_touching=args.include_non_touching,
        feature_set=args.feature_set,
    )
    loaded_before_filter = len(data)
    if args.particle_count is not None:
        data = [graph for graph in data if graph.num_nodes == args.particle_count]
        metadata["particle_count_filter"] = args.particle_count
    else:
        metadata["particle_count_filter"] = None
    n_graphs = len(data)
    print(f"Loaded {loaded_before_filter} valid graphs from {root}")
    if args.particle_count is not None:
        print(
            f"Retained {n_graphs} graphs with exactly "
            f"N={args.particle_count} particles"
        )
    if skipped:
        print(f"Skipped {len(skipped)} invalid graphs; details are saved per candidate")
    if n_graphs < args.folds:
        raise SystemExit(f"Only {n_graphs} valid graphs; need at least {args.folds}")

    candidates = [args.latent] if args.latent is not None else args.latent_candidates
    candidates = sorted(set(candidates))
    if any(dimension < 1 for dimension in candidates):
        raise SystemExit("All latent dimensions must be positive integers")

    order = np.arange(n_graphs)
    folds = (
        np.array_split(np.random.permutation(order), args.folds)
        if args.random_folds
        else make_grouped_folds(data, args.folds, args.seed)
    )
    if args.output_directory is not None:
        result_root = args.output_directory.resolve()
    else:
        particle_label = (
            "all_particle_counts" if args.particle_count is None
            else f"fixed_N_{args.particle_count}"
        )
        result_root = (
            root / "additional_analyses" / particle_label / args.feature_set
            / "exposure_only"
        )
    result_root.mkdir(parents=True, exist_ok=True)
    metadata["result_directory"] = str(result_root)
    print(f"Writing results to {result_root}")

    sweep_directory = result_root / "latent_dimension_sweep"
    results = []
    for latent_dimension in candidates:
        print(f"\nTesting latent dimension {latent_dimension}")
        results.append(run_cross_validation(
            data=data,
            metadata=metadata,
            skipped=skipped,
            folds=folds,
            latent_dimension=latent_dimension,
            output_directory=sweep_directory / f"latent_{latent_dimension}",
            args=args,
        ))

    target_names = metadata["target_names"]
    comparison = [comparison_row(result, target_names) for result in results]
    print_latent_comparison(comparison, target_names)
    with (result_root / "latent_dimension_comparison.csv").open(
        "w", newline="", encoding="utf-8"
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=comparison[0].keys())
        writer.writeheader()
        writer.writerows(comparison)
    if not args.no_plots:
        plot_latent_dimension_comparison(
            comparison,
            target_names,
            result_root / "latent_dimension_comparison.png",
        )

    valid_scores = [
        row["mean_r_squared"] for row in comparison
        if row["mean_r_squared"] is not None
    ]
    if not valid_scores:
        raise RuntimeError("R-squared is undefined for every latent dimension")
    highest_score = max(valid_scores)
    eligible = [
        row for row in comparison
        if row["mean_r_squared"] is not None
        and row["mean_r_squared"] >= highest_score - args.selection_tolerance
    ]
    selected_dimension = min(row["latent_dimension"] for row in eligible)
    selected = next(
        result for result in results
        if result["latent_dimension"] == selected_dimension
    )
    print(
        f"\nSelected latent dimension: {selected_dimension} "
        f"(smallest candidate within {args.selection_tolerance:.3f} mean R2 "
        f"of the maximum)."
    )

    # Publish the selected configuration under the original output names.
    write_prediction_csv(result_root / "predictions.csv", selected["predictions"])
    selected_report = dict(selected["report"])
    selected_report.update({
        "latent_dimension_candidates": candidates,
        "selected_latent_dimension": selected_dimension,
        "selection_rule": (
            "Smallest latent dimension whose mean out-of-fold R-squared is "
            f"within {args.selection_tolerance} of the maximum."
        ),
        "selection_note": (
            "Because the same cross-validation predictions are used for latent-"
            "dimension selection and performance comparison, the selected score "
            "is a model-development estimate. Confirm it with new realizations, "
            "repeated grouped cross-validation, or nested cross-validation."
        ),
        "latent_dimension_comparison": comparison,
        "result_figures": [
            "latent_dimension_comparison.png",
            "gnn_oof_performance.png",
            "gnn_fold_rmse.png",
        ],
    })
    (result_root / "training_metrics.json").write_text(
        json.dumps(selected_report, indent=2) + "\n", encoding="utf-8"
    )
    if not args.no_plots:
        plot_out_of_fold_predictions(
            selected["predictions"],
            target_names,
            selected["report"]["out_of_fold_metrics"],
            result_root / "gnn_oof_performance.png",
        )
        plot_fold_rmse(
            selected["fold_scores"],
            target_names,
            result_root / "gnn_fold_rmse.png",
        )
    for fold_index in range(args.folds):
        shutil.copy2(
            selected["directory"] / f"model_fold_{fold_index}.pt",
            result_root / f"model_fold_{fold_index}.pt",
        )

    print("\nSelected-configuration metrics")
    print(json.dumps(selected_report, indent=2))


if __name__ == "__main__":
    main()
