from pathlib import Path
from tkinter import Tk, filedialog

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress


"""
Created on Sat Jul 04 22:18:53 2026

@author: sp00feR

This method is only reasonable for like up to 300 primary particles, otherwise the memory consumption will be insane

Based on this: 
Rui Wang, Abhinandan Kumar Singh, Subash Reddy Kolan, Evangelos Tsotsas,
Fractal analysis of aggregates: Correlation between the 2D and 3D box-counting fractal dimension and power law fractal dimension,
Chaos, Solitons & Fractals,
Volume 160,
2022,
112246,
ISSN 0960-0779,
https://doi.org/10.1016/j.chaos.2022.112246.
(https://www.sciencedirect.com/science/article/pii/S0960077922004568)
Abstract: Fractal dimension (Df) has been extensively used for many years to characterize the morphological properties of aggregate systems. There are two main methods to estimate the fractal dimension of aggregates, namely the box-counting (BC) and power law (PL) methods. However, the relationship between the BC fractal dimension (Df, BC) and PL fractal dimension (Df, PL) has not been discussed yet. In this work, a series of three-dimensional aggregates with different input parameters (Df, PL and the number of primary particles) is generated by a tunable aggregation model. Then, the fractal dimensions (Df, BC, 3D) of all the aggregates are estimated by the 3D BC method. The relationship between Df, BC, 3D and Df, PL is investigated. We found that Df, BC, 3D is greater than Df, PL when Df, PL≤ 2.5. However, the situation is reversed when Df, PL> 2.5. Further, a novel projection method is proposed and applied to all the 3D aggregates to obtain their 2D projection images. In this projection method, the minimum projection overlapping area of all the primary particles in the aggregate is considered. Then, the fractal dimensions (Df, BC, 2D) of 2D projection images are estimated using the 2D BC method. Finally, correlations between Df, BC, 3D and Df, PL with Df, BC, 2D are established.
Keywords: Aggregation; Box-counting; Power-law; 2D fractal dimension; 3D fractal dimension
"""

#Limiting number Sn used by Wang et al., for higher particle numbers this might have to be decreased?
SN = 256

#create grid divisions according to Fig.2
GRID_DIVISIONS = tuple(
    2 ** exponent
    for exponent in range(1, int(np.log2(SN)) + 1)
)

#this loads the file as csv into np array and returns centers and radii
def load_xyzr_file(filepath):
    data = np.loadtxt(filepath, delimiter=",")

    if data.shape[1] < 4:
        raise ValueError("File must contain x, y, z, r!")

    positions = np.asarray(data[:, :3], dtype=float)
    radii = np.asarray(data[:, 3], dtype=float)
    
    return positions, radii


#basic tk file dialog
def choose_file():
    root = Tk()
    root.withdraw()

    file = filedialog.askopenfilename(
        title="Choose Agglomerate CSV data",
        filetypes=[
            ("CSV Files", "*.txt *.csv *.dat *.xyz"),
            ("All Files", "*.*")
        ]
    )
    root.destroy()
    return file



"""
Domain Construction Method according to Wang et Al:
1. find two primary particles whose centers have the largest distance
2. for this particle pair, calculate coord difference (x1-x2, y1-y2, z1-z2) -> largest one is d
3. calculate cubic side length using L* = d + 2*r_p (Eq. (7))

We center our cubic domain at the middle of the selected particle pair according to Fig.8, they do not mention how they exactly did it tho 

"""

def domain_construction(positions, radii):
    #get aggregate size
    number_of_particles = len(positions)

    #this method is only applicable to monodisperse agglomerates
    primary_radius = float(radii[0])


    #1. find the largest distance pair
    largest_squared_distance = -np.inf
    furthest_i = -1
    furthest_j = -1

    #iterate through all particles
    for i in range(number_of_particles - 1):
        #shorten the pos array according to current index, this changes the index -> furthest_j = i + 1 + local_index
        differences = positions[i + 1:] - positions[i]

        #calculate the coord differences between particle i and all following particls, this is squared but i(d²max) = i(dmax)
        squared_distances = np.einsum(
            "ij,ij->i",
            differences,
            differences,
        )
        #find max for current particle of all the calculated distances
        local_index = int(np.argmax(squared_distances))
        local_squared_distance = float(
            squared_distances[local_index]
        )

        #check wether current pair has the current max distance, if yes -> save the index
        if local_squared_distance > largest_squared_distance:
            largest_squared_distance = local_squared_distance
            furthest_i = i
            furthest_j = i + 1 + local_index

    #save index of largest distance
    particle_a = positions[furthest_i]
    particle_b = positions[furthest_j]

    #2. for this particle pair, calculate coord difference (x1-x2, y1-y2, z1-z2) -> largest one is d
    coordinate_differences = np.abs(particle_a - particle_b)
    d = float(np.max(coordinate_differences))
    
    #3. Eq. (7): L* = d + 2*r_p
    domain_length = d + 2.0 * primary_radius

    #midpoint of the furthest particle pair
    pair_midpoint = 0.5 * (particle_a + particle_b)

    #we center our cube at that point 
    origin = pair_midpoint - 0.5 * domain_length

    return (
        origin,
        domain_length,
        (furthest_i, furthest_j),
        d,
    )


#this method tests wether a sphere intersects with the cubic box, but this step is unfortunately not explained in the paper.... 
#i decided to count a box as occupied if its volume intersects the volume of at least one primary particle
#this works by finding the point inside the box, that is closet to the sphere center, this intersects if the distance is <= particle radius
def sphere_box_intersect(
    sphere_center,
    sphere_radius,
    box_minimum,
    box_maximum,
):
    closest_points = np.clip(
        sphere_center,
        box_minimum,
        box_maximum,
    )

    differences = closest_points - sphere_center

    squared_distances = np.sum(
        differences * differences,
        axis=-1,
    )

    return squared_distances <= sphere_radius ** 2


#this method counts all occupied boxes for one grid resolution 
def count_occupied_boxes(
    positions,
    radii,
    origin,
    domain_length,
    n,
):
    #calculate box size for curent GRID_DIVISION
    box_size = domain_length / n

    #store only occupied box indices instead of the full n³ grid, otherwise this will be memory hogging af
    occupied_boxes = set()

    #iterate through all primary particles
    for center, radius in zip(positions, radii):
        #calculate the minimum and maximum coordinates of the sphere
        sphere_minimum = center - radius
        sphere_maximum = center + radius

        #convert the sphere bounds into grid indices
        minimum_indices = np.floor(
            (sphere_minimum - origin) / box_size
        ).astype(int)

        maximum_indices = np.floor(
            (sphere_maximum - origin) / box_size
        ).astype(int)

        #clip the index range to the valid grid
        minimum_indices = np.clip(
            minimum_indices,
            0,
            n - 1,
        )

        maximum_indices = np.clip(
            maximum_indices,
            0,
            n - 1,
        )

        #generate all possible x indices intersecting the sphere
        x_indices = np.arange(
            minimum_indices[0],
            maximum_indices[0] + 1,
        )
        #generate all possible x indices intersecting the sphere
        y_indices = np.arange(
            minimum_indices[1],
            maximum_indices[1] + 1,
        )
        #generate all possible x indices intersecting the sphere
        z_indices = np.arange(
            minimum_indices[2],
            maximum_indices[2] + 1,
        )

        #create every candidate box around the current sphere
        grid_x, grid_y, grid_z = np.meshgrid(
            x_indices,
            y_indices,
            z_indices,
            indexing="ij",
        )
        
        #combine x,y,z indices into one Nx3 array
        candidate_indices = np.column_stack(
            (
                grid_x.ravel(),
                grid_y.ravel(),
                grid_z.ravel(),
            )
        )

        #calculate lower corner of every candidate box
        candidate_box_minimum = (
            origin + candidate_indices * box_size
        )

        #calculate upper corner of every candidate box
        candidate_box_maximum = (
            candidate_box_minimum + box_size
        )

        #determine which boxes actually intersect the sphere
        intersects = sphere_box_intersect(
            sphere_center=center,
            sphere_radius=radius,
            box_minimum=candidate_box_minimum,
            box_maximum=candidate_box_maximum,
        )

        #keep only intersecting box indices (memory)
        intersected_indices = candidate_indices[intersects]

        #store every occupied box exactly once
        occupied_boxes.update(
            map(tuple, intersected_indices)
        )

    #N(epsilon) = number of occupied boxes
    return len(occupied_boxes)



def calculate_dimension(
    positions,
    radii,
    sn=512,
):
    
    """
    1.calculate L = L* (Eq.7)
    2.divide domain using GRID_DIVISIONS
    3.count N(epsilon), where epsilon = 1/n
    4.fit with lin fit using double log
    
    """
    #construct the domain
    origin, domain_length, furthest_pair, d = (
        domain_construction(positions, radii)
    )

    occupied_counts = []
    n_values = np.asarray(GRID_DIVISIONS, dtype=int)

    #count occupied boxes for all grid divisions
    for n in n_values:
        occupied_count = count_occupied_boxes(
            positions=positions,
            radii=radii,
            origin=origin,
            domain_length=domain_length,
            n=int(n),
        )

        occupied_counts.append(occupied_count)

        print(
            f"n = {n:4d} | "
            f"epsilon = {1.0 / n:.8f} | "
            f"N(epsilon) = {occupied_count}"
        )

    occupied_counts = np.asarray(
        occupied_counts,
        dtype=np.int64,
    )

    # Eq. (5):
    # x = log(1 / epsilon)
    # y = log(N(epsilon))
    # epsilon = 1 / n:
    # x = log(n)
    x = np.log(n_values.astype(float))
    y = np.log(occupied_counts.astype(float))

    regression = linregress(x, y)

    return {
        "fractal_dimension": float(regression.slope),
        "intercept": float(regression.intercept),
        "r_squared": float(regression.rvalue ** 2),
        "standard_error": float(regression.stderr),
        "n_values": n_values,
        "epsilon_values": 1.0 / n_values,
        "occupied_counts": occupied_counts,
        "x": x,
        "y": y,
        "fitted_y": regression.intercept + regression.slope * x,
        "origin": origin,
        "domain_length": domain_length,
        "furthest_pair": furthest_pair,
        "d": d,
        "sn": sn,
    }


#basic matplotlib setup for the box count data and the linear fit
def plot_box_counting_result(result):
    plt.figure(figsize=(8, 6))
    plt.scatter(
        result["x"],
        result["y"],
        label="Box-counting data",
    )
    plt.plot(
        result["x"],
        result["fitted_y"],
        label=(
            rf"Linear fit: "
            rf"$D_{{f,BC,3D}}$ = "
            f"{result['fractal_dimension']:.5f}, "
            rf"$R^2$ = {result['r_squared']:.5f}"
        ),
    )
    plt.xlabel(r"$\log(1/\varepsilon)$")
    plt.ylabel(r"$\log(N(\varepsilon))$")
    plt.title("Box Counting Method (Wang et al.)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    
    plt.show()


def main():
    #pick file
    filepath = choose_file()
    #load file data xyzr
    positions, radii = load_xyzr_file(filepath)

    #Debug
    print("\nLoaded aggregate")
    print("=" * 60)
    print(f"File:               {filepath}")
    print(f"Primary particles:  {len(positions)}")
    print(f"Primary radius Rp:  {radii[0]:.8g}")
    print(f"Limiting number Sn: {SN}")
    print()

    result = calculate_dimension(
        positions=positions,
        radii=radii,
        sn=SN,
    )

    print("\nResult")
    print("=" * 60)
    print(f"d:                  {result['d']:.8g}")
    print(f"Domain length L:    {result['domain_length']:.8g}")
    print(
        f"Df,BC,3D:           "
        f"{result['fractal_dimension']:.8f}"
    )
    print(f"R²:                 {result['r_squared']:.8f}")
    print(
        f"Standard error:     "
        f"{result['standard_error']:.8f}"
    )

    #plot
    plot_box_counting_result(
        result
    )


if __name__ == "__main__":
    main()